# Generated by Django 5.2.7 on 2025-11-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karigar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='karigar_app_is_veri_98a0c6_idx',
        ),
    ]
