# Generated by Django 5.2.7 on 2025-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karigar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('qualifications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
