# Generated by Django 5.2.7 on 2025-11-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('karigar_app', '0002_remove_user_karigar_app_is_veri_98a0c6_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='karigar_app_is_veri_98a0c6_idx'),
        ),
    ]
