# Generated by Django 5.2.7 on 2025-11-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karigar_app', '0003_user_karigar_app_is_veri_98a0c6_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='license_number',
        ),
    ]
