# Generated by Django 5.2.7 on 2025-11-26 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karigar_app', '0004_remove_mechanic_license_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_as_mechanic', to='karigar_app.mechanic'),
        ),
    ]
