# Generated by Django 5.2.7 on 2025-11-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karigar_app', '0005_alter_servicerequest_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests_as_mechanic', to=settings.AUTH_USER_MODEL),
        ),
    ]
